pipeline {
    agent {
        docker {
              image 'node:10'
              args '-v /root/.m2:/root/.m2 -p 3000:3000' 
        }
    }
    stages {
        stage('Set Up') {
            steps {
                script {
                    sh 'rm -rf react-application'
                }
            }
        }
        stage('SCM Checkout') {
            steps {
                sh 'git clone https://github.com/curriculeon-student/jenkins.docker.spring.react.selenium_person-database react-application'
            }
        }
        stage('Compile-Package-Test') {
            steps {
                script {
                    dir('$PWD/react-application/client') {
                        sh "npm install"
                        sh "npm start"
                    }
                }
            }
        }
    }
}
