def projectName = "integrations"

pipeline {
	// ##############################################
	// ##############################################
	// ----------------------------------------------
    agent {
        docker {
            image 'jamesdbloom/docker-java8-maven:latest' 
            args '-u root' 
        }
    }
    stages {
        stage('Set Up') {
            steps {
                script {
                    sh 'rm -rf integrations'
                }
            }
        }
        stage('SCM Checkout') {
            steps {
                sh 'git clone https://github.com/curriculeon-student/jenkins.docker.spring.react.selenium_person-database integrations'
            }
        }
        stage('Compile-Package-Test') {
            steps {
                script {
                    dir('integrations/integration-testing') {
                        sh "mvn package -Dmaven.test.failure.ignore=true"
                    }
                }
            }
        }
    }
	// ----------------------------------------------
	// ##############################################
	// ##############################################
}