pipeline {
    agent {
        docker {
              image 'jamesdbloom/docker-java8-maven:latest' 
              args '-u root -v /root/.m2:/root/.m2 -p 3000:3000'
        }
    }
    stages {
        stage('Set Up') {
            steps {
                script {
                    sh 'rm -rf spring-application'
                }
            }
        }
        stage('SCM Checkout') {
            steps {
                sh 'git clone https://github.com/curriculeon-student/jenkins.docker.spring.react.selenium_person-database spring-application'
            }
        }
        stage('Compile-Package-Test') {
            steps {
                script {
                    dir('$PWD/spring-application/webservice') {
                        sh 'mvn spring-boot:run &'
                    }
                }
            }
        }
    }
}

